from __future__ import annotations

import hashlib
import json
import os
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple, Union

from agentmf.backends import DEFAULT_BACKENDS, SUPPORTED_BACKENDS, GeneratedFile
from agentmf.diagnostics import Diagnostics
from agentmf.ir import normalize
from agentmf.loader import load_source_with_diagnostics_and_paths

BEGIN_MARKER = "<!-- BEGIN GENERATED BY agentmf -->"
END_MARKER = "<!-- END GENERATED BY agentmf -->"
COMPILER_VERSION = "0.1.0"


@dataclass
class TraceEvent:
    phase: str
    message: str
    data: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "phase": self.phase,
            "message": self.message,
            "data": self.data,
        }

    def format(self) -> str:
        if not self.data:
            return f"{self.phase}: {self.message}"
        details = ", ".join(f"{key}={self.data[key]}" for key in sorted(self.data))
        return f"{self.phase}: {self.message} ({details})"


@dataclass
class CompileResult:
    diagnostics: Diagnostics
    files: List[GeneratedFile] = field(default_factory=list)
    wrote: List[Path] = field(default_factory=list)
    unchanged: List[Path] = field(default_factory=list)
    trace: List[TraceEvent] = field(default_factory=list)

    @property
    def ok(self) -> bool:
        return not self.diagnostics.has_errors


def compile_agentmakefile(
    path: Union[Path, str],
    out_dir: Union[Path, str] = ".",
    targets: Optional[List[str]] = None,
    all_backends: bool = False,
    write: bool = False,
    force: bool = False,
    trace: bool = False,
) -> CompileResult:
    diagnostics = Diagnostics()
    trace_events: List[TraceEvent] = []

    def record(phase: str, message: str, data: Optional[Dict[str, Any]] = None) -> None:
        if trace:
            trace_events.append(TraceEvent(phase=phase, message=message, data=data or {}))

    record(
        "start",
        "compile started",
        {
            "path": str(Path(path)),
            "out_dir": str(Path(out_dir)),
            "write": write,
            "force": force,
        },
    )

    if all_backends and targets:
        diagnostics.error("AMF109", "--all cannot be combined with --target")
        record("finish", "compile failed", {"errors": len(diagnostics.items)})
        return CompileResult(diagnostics, trace=trace_events)

    source, load_diagnostics, source_paths = load_source_with_diagnostics_and_paths(path)
    diagnostics.extend(load_diagnostics.items)
    if source is None or diagnostics.has_errors:
        record("load_source", "source failed to load", {"diagnostics": len(load_diagnostics.items)})
        record("finish", "compile failed", {"errors": len(diagnostics.items)})
        return CompileResult(diagnostics, trace=trace_events)

    record(
        "load_source",
        "source loaded",
        {
            "targets": len(source.targets),
            "policies": len(source.policies),
            "skills": len(source.skills),
        },
    )

    selected_targets = _select_targets(source.compile.targets, targets, all_backends)
    record(
        "select_targets",
        "backend targets selected",
        {"targets": selected_targets},
    )
    for target in selected_targets:
        if target not in SUPPORTED_BACKENDS:
            diagnostics.error("AMF103", f"unknown backend target {target}", "compile.targets")

    ir = normalize(source, diagnostics)
    if ir is None or diagnostics.has_errors:
        record("finish", "compile failed", {"errors": len(diagnostics.items)})
        return CompileResult(diagnostics, trace=trace_events)

    record(
        "normalize_ir",
        "IR normalized",
        {
            "targets": len(ir.targets),
            "policies": len(ir.policies),
            "skills": len(ir.skills),
            "permissions": len(ir.permissions),
        },
    )

    files: List[GeneratedFile] = []
    for target in selected_targets:
        emitted_files = SUPPORTED_BACKENDS[target].emit(ir)
        files.extend(emitted_files)
        record(
            "emit_backend",
            f"emitted backend {target}",
            {
                "backend": target,
                "files": [file.path for file in emitted_files],
            },
        )
    if _has_fragment_outputs(files):
        files.append(_build_fragment_manifest(files, source_paths, Path(path)))
        record("emit_manifest", "emitted fragment manifest", {"path": ".agentmf/fragments/manifest.json"})

    result = CompileResult(diagnostics=diagnostics, files=files, trace=trace_events)
    if write and not diagnostics.has_errors:
        _write_files(Path(out_dir), files, force, diagnostics, result)
        for wrote in result.wrote:
            record("write_file", "wrote generated file", {"path": str(wrote)})
        for unchanged in result.unchanged:
            record("write_file", "generated file unchanged", {"path": str(unchanged)})
    record(
        "finish",
        "compile finished" if result.ok else "compile failed",
        {
            "ok": result.ok,
            "files": [file.path for file in result.files],
            "wrote": [str(path) for path in result.wrote],
            "unchanged": [str(path) for path in result.unchanged],
        },
    )
    return result


def _select_targets(
    configured_targets: List[str],
    requested_targets: Optional[List[str]],
    all_backends: bool,
) -> List[str]:
    if all_backends:
        return list(SUPPORTED_BACKENDS)
    if requested_targets:
        return requested_targets
    if configured_targets:
        return configured_targets
    return list(DEFAULT_BACKENDS)


def _has_fragment_outputs(files: List[GeneratedFile]) -> bool:
    return any(file.metadata.get("kind") == "target-fragment" for file in files)


def _build_fragment_manifest(files: List[GeneratedFile], source_paths: List[Path], root_path: Path) -> GeneratedFile:
    source_inputs = _source_input_paths(source_paths, root_path)
    fragments = []
    for file in files:
        if file.metadata.get("kind") != "target-fragment":
            continue
        fragments.append(
            {
                "backend": file.backend,
                "target": file.metadata["target"],
                "path": file.path,
                "target_closure": file.metadata["target_closure"],
                "inputs": source_inputs,
                "policies": file.metadata["policies"],
                "skills": file.metadata["skills"],
                "hash": f"sha256:{_content_hash(file.content)}",
            }
        )
    manifest = {
        "version": 1,
        "compiler_version": COMPILER_VERSION,
        "fragments": sorted(fragments, key=lambda item: item["path"]),
    }
    return GeneratedFile(
        path=".agentmf/fragments/manifest.json",
        content=json.dumps(manifest, indent=2, sort_keys=True) + "\n",
        backend="fragment-manifest",
        managed_block=False,
        overwrite=True,
    )


def _source_input_paths(source_paths: List[Path], root_path: Path) -> List[str]:
    root_dir = root_path.resolve().parent
    rendered = []
    seen = set()
    for path in source_paths:
        relative = os.path.relpath(path.resolve(), root_dir).replace(os.sep, "/")
        if relative in seen:
            continue
        seen.add(relative)
        rendered.append(relative)
    return rendered


def _content_hash(content: str) -> str:
    return hashlib.sha256(content.encode()).hexdigest()


def _write_files(
    out_dir: Path,
    files: List[GeneratedFile],
    force: bool,
    diagnostics: Diagnostics,
    result: CompileResult,
) -> None:
    write_plan: List[Tuple[Path, str]] = []
    for generated in files:
        target = out_dir / generated.path
        if generated.managed_block:
            content = _managed_content(target, generated.content, force, diagnostics)
            if content is None:
                continue
            write_plan.append((target, content))
        else:
            if target.exists() and not force and not generated.overwrite:
                diagnostics.error(
                    "AMF110",
                    "refusing to overwrite existing generated artifact without --force",
                    str(target),
                    "pass --force or choose a different artifacts.<backend>.path",
                )
                continue
            write_plan.append((target, generated.content))

    if diagnostics.has_errors:
        return

    for target, content in write_plan:
        target.parent.mkdir(parents=True, exist_ok=True)
        if target.exists() and target.read_text() == content:
            result.unchanged.append(target)
            continue
        target.write_text(content)
        result.wrote.append(target)


def _managed_content(target: Path, generated_content: str, force: bool, diagnostics: Diagnostics) -> Optional[str]:
    block = f"{BEGIN_MARKER}\n{generated_content.rstrip()}\n{END_MARKER}\n"
    if not target.exists():
        return block

    existing = target.read_text()
    begin = existing.find(BEGIN_MARKER)
    end = existing.find(END_MARKER)
    if begin == -1 and end == -1:
        if not force:
            diagnostics.error(
                "AMF111",
                "managed block missing in existing shared output",
                str(target),
                "pass --force to append a managed block or configure a dedicated artifact path",
            )
            return None
        separator = "" if existing.endswith("\n") else "\n"
        return f"{existing}{separator}\n{block}"
    if existing.count(BEGIN_MARKER) != 1 or existing.count(END_MARKER) != 1 or begin == -1 or end == -1 or end < begin:
        diagnostics.error("AMF112", "managed block is malformed", str(target))
        return None

    end_index = end + len(END_MARKER)
    prefix = existing[:begin]
    suffix = existing[end_index:]
    return f"{prefix}{block.rstrip()}{suffix}"
