from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import List, Optional, Union

from agentmf.backends import DEFAULT_BACKENDS, SUPPORTED_BACKENDS, GeneratedFile
from agentmf.diagnostics import Diagnostics
from agentmf.ir import normalize
from agentmf.loader import load_source_with_diagnostics

BEGIN_MARKER = "<!-- BEGIN GENERATED BY agentmf -->"
END_MARKER = "<!-- END GENERATED BY agentmf -->"


@dataclass
class CompileResult:
    diagnostics: Diagnostics
    files: List[GeneratedFile] = field(default_factory=list)
    wrote: List[Path] = field(default_factory=list)

    @property
    def ok(self) -> bool:
        return not self.diagnostics.has_errors


def compile_agentmakefile(
    path: Union[Path, str],
    out_dir: Union[Path, str] = ".",
    targets: Optional[List[str]] = None,
    all_backends: bool = False,
    write: bool = False,
    force: bool = False,
) -> CompileResult:
    diagnostics = Diagnostics()
    if all_backends and targets:
        diagnostics.error("AMF109", "--all cannot be combined with --target")
        return CompileResult(diagnostics)

    source, load_diagnostics = load_source_with_diagnostics(path)
    diagnostics.extend(load_diagnostics.items)
    if source is None or diagnostics.has_errors:
        return CompileResult(diagnostics)

    selected_targets = _select_targets(source.compile.targets, targets, all_backends)
    for target in selected_targets:
        if target not in SUPPORTED_BACKENDS:
            diagnostics.error("AMF103", f"unknown backend target {target}", "compile.targets")

    ir = normalize(source, diagnostics)
    if ir is None or diagnostics.has_errors:
        return CompileResult(diagnostics)

    files: List[GeneratedFile] = []
    for target in selected_targets:
        files.extend(SUPPORTED_BACKENDS[target].emit(ir))

    result = CompileResult(diagnostics=diagnostics, files=files)
    if write and not diagnostics.has_errors:
        _write_files(Path(out_dir), files, force, diagnostics, result)
    return result


def _select_targets(
    configured_targets: List[str],
    requested_targets: Optional[List[str]],
    all_backends: bool,
) -> List[str]:
    if all_backends:
        return list(SUPPORTED_BACKENDS)
    if requested_targets:
        return requested_targets
    if configured_targets:
        return configured_targets
    return list(DEFAULT_BACKENDS)


def _write_files(
    out_dir: Path,
    files: List[GeneratedFile],
    force: bool,
    diagnostics: Diagnostics,
    result: CompileResult,
) -> None:
    for generated in files:
        target = out_dir / generated.path
        target.parent.mkdir(parents=True, exist_ok=True)
        if generated.managed_block:
            content = _managed_content(target, generated.content, force, diagnostics)
            if content is None:
                continue
            target.write_text(content)
        else:
            if target.exists() and not force:
                diagnostics.error(
                    "AMF110",
                    "refusing to overwrite existing generated artifact without --force",
                    str(target),
                    "pass --force or choose a different artifacts.<backend>.path",
                )
                continue
            target.write_text(generated.content)
        result.wrote.append(target)


def _managed_content(target: Path, generated_content: str, force: bool, diagnostics: Diagnostics) -> Optional[str]:
    block = f"{BEGIN_MARKER}\n{generated_content.rstrip()}\n{END_MARKER}\n"
    if not target.exists():
        return block

    existing = target.read_text()
    begin = existing.find(BEGIN_MARKER)
    end = existing.find(END_MARKER)
    if begin == -1 and end == -1:
        if not force:
            diagnostics.error(
                "AMF111",
                "managed block missing in existing shared output",
                str(target),
                "pass --force to append a managed block or configure a dedicated artifact path",
            )
            return None
        separator = "" if existing.endswith("\n") else "\n"
        return f"{existing}{separator}\n{block}"
    if begin == -1 or end == -1 or end < begin:
        diagnostics.error("AMF112", "managed block is malformed", str(target))
        return None

    end_index = end + len(END_MARKER)
    prefix = existing[:begin]
    suffix = existing[end_index:]
    return f"{prefix}{block.rstrip()}{suffix}"
